apiVersion: v2
name: newrelic-prometheus-agent
description: A Helm chart to deploy Prometheus with New Relic Prometheus Configurator.
type: application
version: 2.4.2
# Prometheus Server Version
# https://pkg.go.dev/github.com/prometheus/prometheus#readme-prometheus-code-base
appVersion: "v3.7.0-rc.0"
annotations:
  configuratorVersion: "2.4.2"
dependencies:
  - name: common-library
    version: 1.3.3
    repository: "https://helm-charts.newrelic.com"
keywords:
  - newrelic
  - prometheus
maintainers:
  - name: juanjjaramillo
    url: https://github.com/juanjjaramillo
  - name: csongnr
    url: https://github.com/csongnr
  - name: dbudziwojskiNR
    url: https://github.com/dbudziwojskiNR
