apiVersion: v2
name: newrelic-prometheus-agent
description: A Helm chart to deploy Prometheus with New Relic Prometheus Configurator.
type: application
version: 2.6.1
# Prometheus Server Version
# https://pkg.go.dev/github.com/prometheus/prometheus#readme-prometheus-code-base
appVersion: "v3.8.0"
annotations:
  configuratorVersion: "2.6.1"
dependencies:
  - name: common-library
    version: 1.4.0
    repository: "https://helm-charts.newrelic.com"
keywords:
  - newrelic
  - prometheus
maintainers:
  - name: juanjjaramillo
    url: https://github.com/juanjjaramillo
  - name: csongnr
    url: https://github.com/csongnr
  - name: dbudziwojskiNR
    url: https://github.com/dbudziwojskiNR
